BotName = 'wolfcord test'

KeyLoc = 'C:\Users\gavin\.token\wolfricTest'
ServerID = '1236019728443641896' #CorpoWolf Server

[Database]
host = 'wolfstone.xyz'
port = 5432
user = 'sawyer'
password = 'C:\Users\gavin\.token\iwaitPostgres'
dbname = 'canoebot'

[[Whitelist]]
id = '106951670512037888'
name = 'Sawyer'

[[Whitelist]]
id = '800158702132133898'
name = 'Fovero'